"""agregar_titulo_a_informes

Revision ID: 970fd31264a6
Revises: a4cfd29be7f5
Create Date: 2026-06-29 07:19:53.563772+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '970fd31264a6'
down_revision: Union[str, None] = 'a4cfd29be7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###